### ISSUE TITLE
please bump package version of github.com/quic-go/quic-go

### ISSUE THREAD

**Issue by luckykeeper** [honwen/golibs#2]
Hello there~
I'm using cip with go1.21.0 and can't pass complie, error is
```powershell
go build
# github.com/quic-go/quic-go/internal/handshake
..\..\pkg\mod\github.com\quic-go\quic-go@v0.37.0\internal\handshake\crypto_setup.go:334:37: cannot use h.allow0RTT (variable of type bool) as tls.QUICSessionTicketOptions value in argument to h.conn.SendSessionTicket
```

more detailed info can be seen here: https://github.com/quic-go/quic-go/issues/4021

Thank you.

**Comment by honwen** [comment]
add `replace` like https://github.com/honwen/golibs/blob/master/go.mod#L38 to Ur `go.mod`

**Comment by luckykeeper** [comment]
It's okay, got it. Thanks a lot!
